# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Assisstant_DFCI
                                 A QGIS plugin
 Contribution directe (DFCI)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-04
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PIL.features import features
from PyQt5.QtWidgets import QComboBox, QLineEdit, QLabel

from PyQt5.QtGui import QIntValidator
from collections import Counter
from qgis.core import Qgis, QgsMapLayer

from .assisstant_dfci_dialog import Assisstant_DFCIDialog
from .fonction import  *
from .cheminpluscourt import *
import xml.etree.ElementTree as ET
from .aproposde import Aproposde

class Assisstant_DFCI:
    """
    IMPORTANT : le nom (objectName) des CComboBox doivent avoir une correspondance
    avec un champs dans le xml.
    """
    # retourne la liste des widgets dans le formlayout
    def get_widgets(self,type_widget = "ALL"):
        list_combo = []
        list_line_edit = []
        list_label = []

        widgets = self.dlg.children()
        for widg in widgets:
            if widg.objectName() == "formLayoutWidget":
                children = widg.children()
                for child in children:
                    if (type_widget == "QLineEdit"
                            or type_widget == "ALL") and isinstance(child, QLineEdit):
                        list_line_edit.append(child)
                    elif (type_widget == "QComboBox"
                          or type_widget == "ALL") and isinstance(child, QComboBox):
                        list_combo.append(child)
                    elif type_widget == "QLabel" and isinstance(child, QLabel):
                        list_label.append(child)

        tmp = list_line_edit + list_combo + list_label
        return tmp

    # initialise tous les combobox avec les attributs issus du xml
    # et return : le dictionnaire
    # clé : champs
    # valeur = tous les attributs possibles
    def ini_widget(self):
        # parcours des widgets combobox inclu dans le formLayouWidget
        # et remplissage d'une liste de QComboBox
        list_widget = self.get_widgets("QComboBox")

        # initialisation du dictionnaire des champs, attributs associés
        # à partir du xml
        dico_champs_val_xml = {}
        tree = ET.parse(PATH_REP + "\XML\Attributs.xml")
        root = tree.getroot()
        for champs in root.findall("champs"):
            # il faut reinitialiser la liste, pas juste la vider
            list_valeur = []
            champs_id = champs.get('id')
            for valeur in champs.findall("valeur"):
                list_valeur.append(valeur.text)
            dico_champs_val_xml[champs_id] = list_valeur

        # initialisation des combo a vide
        for champs, valeur in dico_champs_val_xml.items():
            for widg in list_widget:
                if champs == widg.objectName():
                    widg.clear()

        # comparaison entre les CComboBox de l'interface et ceux du xml
        # et remplissage des combos
        for champs, valeur in dico_champs_val_xml.items():
            for widg in list_widget:
                if champs == widg.objectName():
                    widg.addItems(valeur)


    def islayer_espaceco(self):
        project = QgsProject.instance()
        if not project.fileName():
            QMessageBox.warning(None, "Avertissement", "Veuillez charger un projet")
            return False

        text = f"Une ou plusieurs couches suivantes ne sont pas accessibles :<br>"
        isok = True
        for layer_espace_co in LAYER_ESPACE_CO:
            layer = project.mapLayersByName(layer_espace_co)
            if not layer:
                text += f"<b>{layer_espace_co}</b><br>"
                isok = False
        if not isok:
            QMessageBox.warning(None,"Avertissement",text)
            return False
        else:
            layer = project.mapLayersByName(LAYER_ESPACE_CO[0])
            self.layer_route = layer[0]
            layer = project.mapLayersByName(LAYER_ESPACE_CO[1])
            self.layer_complexe_route = layer[0]
            return True

    def afficheMessageBar(self, message):
        self.iface.messageBar().pushMessage("Info", message, level=Qgis.Info, duration=5)

    def set_active_layer(self,layer):
        project = QgsProject.instance()
        couche = project.mapLayersByName(layer)
        self.iface.setActiveLayer(couche[0])
        self.layer = self.iface.activeLayer()

    # recuperer les attributs d'un objet selectionné en fonction du nom des champs
    def set_info_route_in_label(self,nom_champs):
        self.dlg.textEdit_info_route.setText("")
        self.dlg.textEdit_info_complexe.setText("")
        if self.layer.selectedFeatureCount() == 0:
            return

        routes_nommees = []
        dico_rte_nommee = {}
        for sel in self.layer.selectedFeatures():
            routes_nommees += sel[nom_champs].split("/")
            # Il faut tester si la valeur existe avant d'enlever sinon plantage
            if "NULL" in routes_nommees:
                routes_nommees.remove("NULL")
            if "" in routes_nommees:
                routes_nommees.remove("")

        # suppression des doublons
        list_complexe_unique = list(set(routes_nommees))

        # est-ce que 1 troncon peut pointer sur plusieurs complexes DFCI ?
        isDFCI = []
        complexe = ""
        for complexe in list_complexe_unique:
            type_dfci = self.get_attributs_entite(LAYER_ESPACE_CO[1], CLEABS, complexe, TYPE_ROUTE)
            dico_rte_nommee[complexe] = type_dfci
            self.dlg.textEdit_info_route.append(f"{complexe} :<b> Type = <span style='color: red'>{type_dfci}</b></span>")
            # on récupère les infos que sur les complexes de type DFCI
            if type_dfci == TYPE_ROUTE_DFCI:
                isDFCI.append(True)
            else:
                isDFCI.append(False)

        if len(isDFCI) == 1 and any(isDFCI):
            cleabs = self.get_attributs_entite(LAYER_ESPACE_CO[1], CLEABS, complexe, CLEABS)
            self.dlg.textEdit_info_complexe.append(f"Cleabs piste DFCI : {cleabs}")
            gestionnaire = self.get_attributs_entite(LAYER_ESPACE_CO[1], CLEABS, complexe,GESTIONNAIRE)
            self.dlg.textEdit_info_complexe.append(f"Gestionnaire\t      : {gestionnaire}")
            numero = self.get_attributs_entite(LAYER_ESPACE_CO[1], CLEABS, complexe,NUMERO)
            self.dlg.textEdit_info_complexe.append(f"Numéro\t      : {numero}")
            toponyme = self.get_attributs_entite(LAYER_ESPACE_CO[1], CLEABS, complexe,TOPONYME)
            self.dlg.textEdit_info_complexe.append(f"Toponyme\t      : {toponyme}")

    def vide_attribut_widgets(self):
        for widget_inerface in self.get_widgets("QLineEdit"):
            widget_inerface.setText("")
            widget_inerface.setStyleSheet(CUSTOM_WIDGETS[2])
        for widget_inerface in self.get_widgets("QComboBox"):
            widget_inerface.setCurrentIndex(0)
            widget_inerface.setStyleSheet(CUSTOM_WIDGETS[2])

    def get_attributs_entite(self,layer,nom_champs,valeur,champs_renvoye):
        project = QgsProject.instance()
        layer1 = project.mapLayersByName(layer)

        # self.set_active_layer(layer)
        features = layer1[0].getFeatures()
        for feature in features:
            if feature[nom_champs] == valeur:
                return feature[champs_renvoye]

    def init_widgets_from_selection(self):

        self.vide_attribut_widgets()
        """"***************
        traitement des occurence pour recherche des attributs communs
        ****************"""
        # COMBOBOX
        list_attr = []
        for widg in self.get_widgets("QComboBox"):
            list_attr.clear()
            widg.setStyleSheet(CUSTOM_WIDGETS[2])
            for sel in self.layer.selectedFeatures():
                # suppr le try quand la categorie dfci sera en ecriture dans le guichet
                try:
                    list_attr.append(str(sel[widg.objectName()]))
                    list_attr = ["Non" if val == "0" else "Oui" if val == "1" else val for val in list_attr]
                except KeyError:
                    pass
            compte = Counter(list_attr)
            for elem, count in compte.items():
                if count == self.layer.selectedFeatureCount():
                    widg.setCurrentText(list_attr[0])
                    if list_attr[0] != "NULL":
                        widg.setStyleSheet(CUSTOM_WIDGETS[0])

        # LINEEDIT
        for widg in self.get_widgets("QLineEdit"):
            list_attr.clear()
            widg.setStyleSheet(CUSTOM_WIDGETS[2])
            for sel in self.layer.selectedFeatures():
                # suppr le try quand la categorie dfci sera en ecriture dans le guichet
                    list_attr.append(sel[widg.objectName()])

            compte = Counter(list_attr)
            for elem, count in compte.items():
                # toutes valeurs identiques (=valeurs communes)
                if count == self.layer.selectedFeatureCount():
                    # en vert
                    widg.setText(str(list_attr[0]))
                    if list_attr[0] != "NULL":
                        # en vert
                        widg.setStyleSheet(CUSTOM_WIDGETS[0])
                    else:
                        # pas de fond
                        widg.clear()
                        widg.setStyleSheet(CUSTOM_WIDGETS[2])
                else:
                    widg.setStyleSheet(CUSTOM_WIDGETS[2])


    def valider_transaction(self):
        if len(self.dico_champs_modifie) == 0:
            return

        QGuiApplication.setOverrideCursor(Qt.WaitCursor)
        self.layer.startEditing()
        for sel in self.layer.selectedFeatures():

            # changement d'attributs par paquet (dico de valeurs)
            if not self.layer.changeAttributeValues(sel.id(), self.dico_champs_modifie):
                print("Erreur: changement d'attribut non effectué")
        QGuiApplication.restoreOverrideCursor()
        self.afficheMessageBar(
            f"Les modifications ont été effectués sur : {self.layer.selectedFeatureCount()} tronçon(s)")

    def set_enable_widget(self,etat = True):
        for widget_inerface in self.get_widgets("QLineEdit"):
            widget_inerface.setEnabled(etat)
        for widget_inerface in self.get_widgets("QComboBox"):
            widget_inerface.setEnabled(etat)

    def actualiserSelection(self):
        # gestion de la couleur de selection
        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)

        self.dlg.pushButtonValider.setEnabled(False)
        self.layer = self.iface.activeLayer()
        if self.layer != self.layer_route:
            self.set_enable_widget(False)
            return

        if self.layer.selectedFeatureCount() == 2:
            self.dlg.pushButtonCheminCourt.setEnabled(True)
        else:
            self.dlg.pushButtonCheminCourt.setEnabled(False)

        if self.layer.selectedFeatureCount() == 0:
            self.vide_attribut_widgets()
            self.dlg.textEdit_info_complexe.clear()
            self.dlg.textEdit_info_route.clear()
            self.set_enable_widget(False)
        else:
            self.set_enable_widget()

        self.dico_champs_modifie.clear()
        # self._list_selection = self.layer.selectedFeatures()
        self.set_info_route_in_label(LIEN_VERS_RTE_NOMMEE)
        self.init_widgets_from_selection()

        self.dlg.labelnbselection.setText(f"Vous avez sélectionné : <span style='color: red'><b>{self.layer.selectedFeatureCount()}</b></span> tronçon(s)")


    def edit_Change_utilisateur(self,widget_interface):

        index_champs = self.layer.fields().indexOf(widget_interface.objectName())
        if widget_interface.text() == "":
            self.dico_champs_modifie[index_champs] = "NULL"
        else:
            self.dico_champs_modifie[index_champs] = widget_interface.text()
        self.dlg.pushButtonValider.setEnabled(True)

    def combo_Change_utilisateur(self,widget_interface):
        index_champs = self.layer.fields().indexOf(widget_interface.objectName())
        valeur = widget_interface.currentText()
        if valeur == "Non":
            valeur = 0
        elif valeur == "Oui":
            valeur = 1
        else:
            valeur = widget_interface.currentText()
        self.dico_champs_modifie[index_champs] = valeur
        self.dlg.pushButtonValider.setEnabled(True)

    def widgetChange(self,widget_interface):
        if self.layer.selectedFeatureCount() == 0:
            return
        widget_interface.setStyleSheet(CUSTOM_WIDGETS[1])

    def chemin_court(self):
        if self.layer.selectedFeatureCount() != 2:
            QMessageBox.warning(None,TITRE,"Veuillez sélectionner 2 tronçons")
            return
            # instanciation de la class dhemin le plus court
        self.cheminpluscourt = cheminpluscourt(self.iface, self.layer)
        self.cheminpluscourt.cheminpluscourt()

        self.set_active_layer(LAYER_ESPACE_CO[0])
        self.actualiserSelection()

    def affiche_sens(self):
        if self.is_affiche_sens_num:
            self.layer.loadNamedStyle(os.path.join(PATH_REP ,"SENS_NUM", "sauvegarde_style_route.qml"),categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)
            self.is_affiche_sens_num = False
        else:
            self.layer.saveNamedStyle(os.path.join(PATH_REP ,"SENS_NUM", "sauvegarde_style_route.qml"),categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)
            self.layer.loadNamedStyle(os.path.join(PATH_REP ,"SENS_NUM","style_sens_numerisation.qml"),categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)
            self.is_affiche_sens_num = True
        self.layer.triggerRepaint()

    def a_propos(self):
        self.dlgAProposDe.show()

    def __init__(self, iface):
        self.dlgAProposDe = None
        self.dlg = None
        self.cheminpluscourt = None
        self.layer = None

        self.layer_route = None
        self.layer_complexe_route = None
        self.iface = iface
        self.is_affiche_sens_num = False

        # dico des champs modifiés
        # cle = id champs
        # valeur = attributs
        self.dico_champs_modifie = {}

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True

    def colorchange(self):
        self.actualiserSelection()

    def initGui(self):
        pass

    def unload(self):
        pass

    def run(self):
        """Run method that performs all the real work"""

        # est ce que les layer de l'espace co sont disponibles
        if not self.islayer_espaceco():
            return
        self.set_active_layer(LAYER_ESPACE_CO[0])
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False

            self.dlg = Assisstant_DFCIDialog()
            self.dlg.setWindowTitle(f"{TITRE}  {VERSION}")
            self.dlgAProposDe = Aproposde()
            self.dlgAProposDe.pushButtonDoc.clicked.connect(afficheDoc)

            self.dlg.textEdit_info_route.setText("")
            self.dlg.textEdit_info_complexe.setText("")

            self.dlg.labelnbselection.setText("")

            self.dlg.mColorButton.colorChanged.connect(self.colorchange)
            self.dlg.mColorButton.setColor(self.iface.mapCanvas().selectionColor())

            # a propos de
            self.dlgAProposDe.setWindowFlags(Qt.WindowStaysOnTopHint|Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
            self.dlg.pushButtonAPropos.clicked.connect(self.a_propos)
            self.dlgAProposDe.setWindowTitle(f"{TITRE}  {VERSION}")

            self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)

            if self.layer.selectedFeatureCount() !=2:
                self.dlg.pushButtonCheminCourt.setEnabled(False)
            self.dlg.pushButtonCheminCourt.clicked.connect(self.chemin_court)
            self.dlg.pushButtonSensNum.clicked.connect(self.affiche_sens)

            # evenement des widgets
            for widget_interface in self.get_widgets("QLineEdit"):
                widget_interface.textChanged.connect(lambda _, w1=widget_interface :self.widgetChange(w1))
                widget_interface.setValidator(QIntValidator())
            for widget_interface in self.get_widgets("QComboBox"):
                widget_interface.currentTextChanged.connect(lambda _, w2=widget_interface :self.widgetChange(w2))

            # modif par l'utilisateur line edit
            for widget_interface in self.get_widgets("QLineEdit"):
                # textedited : changement par l'utilisateur, donc autre que par setText()
                widget_interface.textEdited.connect(lambda _, w3=widget_interface :self.edit_Change_utilisateur(w3))

            #  modif par l'utilisateur combobox
            for widget_interface in self.get_widgets("QComboBox"):
                widget_interface.activated.connect(lambda _, w3=widget_interface: self.combo_Change_utilisateur(w3))


            for widget_interface in self.get_widgets("QLabel"):
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[4])

            self.dlg.pushButtonValider.clicked.connect(self.valider_transaction)
            self.dlg.pushButtonValider.setStyleSheet(CUSTOM_WIDGETS[3])

            self.layer.saveNamedStyle(os.path.join(PATH_REP, "SENS_NUM", "sauvegarde_style_route.qml"))

            # initialisation des widgets avec tous les attributs du xml
            self.ini_widget()
            self.actualiserSelection()

        # show the dialog
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if not result:
            self.layer.loadNamedStyle(os.path.join(PATH_REP, "SENS_NUM", "sauvegarde_style_route.qml"),categories=QgsMapLayer.StyleCategory.Symbology| QgsMapLayer.Labeling)
            self.layer.triggerRepaint()
            self.dlgAProposDe.hide()
            self.is_affiche_sens_num = False

